### ISSUE TITLE
Keep youtube skip time

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Embed-API#2]
At the moment we don't keep the tagged time of YouTube Videos. ?t=1234

**Comment by MarcoBomfim** [comment]
@appinteractive, is this still needed? 

Would like to try it out for my first contribution.

**Comment by roschaefer** [comment]
@MarcoBomfim Yes, please! :heart_eyes: did you join our community Discord server already? https://discord.gg/6ub73U3

**Comment by MarcoBomfim** [comment]
No, I haven't. Will do though.

**Comment by roschaefer** [comment]
We run at least one weekly Open Source community developer meeting. Additional pair-programmings in the meantime. Interested?

Our last meeting: https://youtu.be/ozCp9CfsUzc

**Comment by MarcoBomfim** [comment]
Sure! 

Nice way to get some more knowledge and experience. I'll assign this issue and start working on it then.

**Comment by MarcoBomfim** [comment]
I think we can close this one out
