### ISSUE TITLE
Embedding YT Playlists does not work

### ISSUE THREAD

**Issue by ghost** [Human-Connection/Embed-API#3]
embedding a direct video works fine, embedding a playlist will mess up the link.

**Comment by MarcoBomfim** [comment]
@appinteractive, was thinking about taking this one after [PR-19](https://github.com/Human-Connection/Embed-API/pull/19) gets merged. 

This is probably going to require me to change the RegEx again to include the playlist params, as well as the tests for all Youtube URLs.

**Comment by roschaefer** [comment]
@MarcoBomfim same same in #34 you can fix both

@MarcoBomfim it would be great to invest some research if there are existing solutions to this out there. Metaphor is not maintained and officially deprecated after all. So maybe we can add some library that does the parsing of youtube links for us?

**Comment by roschaefer** [comment]
Regular expressions are hard to maintain. There is a saying: "As soon as you learn to solve a problem with a regular expression, you have another problem."

**Comment by mbomfim33** [comment]
Hey @roschaefer can we close this one? 😄

**Comment by roschaefer** [comment]
Hey @MarcoBomfim this repository along with the main one is not being maintained anymore. Development continues in https://github.com/Ocelot-Social-Community/Ocelot-Social.

**Comment by mbomfim33** [comment]
Thanks @roschaefer! I thought the project was discontinued, glad to read it is still going on. I might get back and do some contributing 💯
